name: Django Unit Tests

on:
  pull_request:
    branches: ["develop", "main"]
  push:
    branches: ["unittests"]   # testing

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install coverage

      - name: Run tests with coverage
        run: |
          coverage run manage.py test
          coverage report -m
          coverage xml

      - name: Comment coverage on PR
        uses: mattallty/comment-on-pr@v1.0.2
        if: ${{ github.event_name == 'pull_request' }}
        with:
          msg: |
            **Test Coverage Report**
            ```
            $(coverage report)
            ```
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}